-- El Kady Menu — 12 categories, 95 items (6 with small/large variants → 101 rows)
-- Source: /home/mustafa-tag-eldeen/Downloads/El_Kady_Menu.xlsx (96 rows inc. header)
-- Generated: categories ordered by XLSX appearance, items sorted by category sort + XLSX order

begin;

-- Clear existing seed (12 items, 4 categories) — keep FK order
delete from menu_items;
delete from menu_categories;
-- Reset category id seq for deterministic ids
select setval('menu_categories_id_seq', 1, false);

-- Categories
insert into menu_categories (id, slug, name_ar, name_en, sort) values (1, 'turkish-coffee', 'قهوة تركي', 'Turkish Coffee', 1) on conflict (id) do update set slug=excluded.slug, name_ar=excluded.name_ar, name_en=excluded.name_en, sort=excluded.sort;
insert into menu_categories (id, slug, name_ar, name_en, sort) values (2, 'espresso', 'اسبريسو', 'Espresso', 2) on conflict (id) do update set slug=excluded.slug, name_ar=excluded.name_ar, name_en=excluded.name_en, sort=excluded.sort;
insert into menu_categories (id, slug, name_ar, name_en, sort) values (3, 'hot-drinks', 'مشروبات ساخنة', 'Hot Drinks', 3) on conflict (id) do update set slug=excluded.slug, name_ar=excluded.name_ar, name_en=excluded.name_en, sort=excluded.sort;
insert into menu_categories (id, slug, name_ar, name_en, sort) values (4, 'iced-espresso', 'ايس اسبريسو', 'Iced Espresso', 4) on conflict (id) do update set slug=excluded.slug, name_ar=excluded.name_ar, name_en=excluded.name_en, sort=excluded.sort;
insert into menu_categories (id, slug, name_ar, name_en, sort) values (5, 'frappuccino', 'فرابتشينو', 'Frappuccino', 5) on conflict (id) do update set slug=excluded.slug, name_ar=excluded.name_ar, name_en=excluded.name_en, sort=excluded.sort;
insert into menu_categories (id, slug, name_ar, name_en, sort) values (6, 'desserts', 'حلوى', 'Desserts', 6) on conflict (id) do update set slug=excluded.slug, name_ar=excluded.name_ar, name_en=excluded.name_en, sort=excluded.sort;
insert into menu_categories (id, slug, name_ar, name_en, sort) values (7, 'waffle', 'وافل', 'Waffle', 7) on conflict (id) do update set slug=excluded.slug, name_ar=excluded.name_ar, name_en=excluded.name_en, sort=excluded.sort;
insert into menu_categories (id, slug, name_ar, name_en, sort) values (8, 'fruit-salad', 'سلطة فواكه', 'Fruit Salad', 8) on conflict (id) do update set slug=excluded.slug, name_ar=excluded.name_ar, name_en=excluded.name_en, sort=excluded.sort;
insert into menu_categories (id, slug, name_ar, name_en, sort) values (9, 'ice-cream', 'ايس كريم', 'Ice Cream', 9) on conflict (id) do update set slug=excluded.slug, name_ar=excluded.name_ar, name_en=excluded.name_en, sort=excluded.sort;
insert into menu_categories (id, slug, name_ar, name_en, sort) values (10, 'bakery', 'مخبوزات', 'Bakery', 10) on conflict (id) do update set slug=excluded.slug, name_ar=excluded.name_ar, name_en=excluded.name_en, sort=excluded.sort;
insert into menu_categories (id, slug, name_ar, name_en, sort) values (11, 'extras', 'الاضافات', 'Extras', 11) on conflict (id) do update set slug=excluded.slug, name_ar=excluded.name_ar, name_en=excluded.name_en, sort=excluded.sort;
insert into menu_categories (id, slug, name_ar, name_en, sort) values (12, 'winter-specials', 'شتاء القاضي', 'Winter Specials', 12) on conflict (id) do update set slug=excluded.slug, name_ar=excluded.name_ar, name_en=excluded.name_en, sort=excluded.sort;

-- Items (price_egp = single price; two-price items split into small/large variants)

insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('turkish-coffee-قهوة-القاضي-small', 'قهوة القاضي صغير', 'قهوة القاضي صغير', '', '', 35, 1, 1, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('turkish-coffee-قهوة-القاضي-large', 'قهوة القاضي كبير', 'قهوة القاضي كبير', '', '', 50, 1, 2, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('turkish-coffee-قهوة-فرنساوي-small', 'قهوة فرنساوي صغير', 'قهوة فرنساوي صغير', '', '', 45, 1, 3, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('turkish-coffee-قهوة-فرنساوي-large', 'قهوة فرنساوي كبير', 'قهوة فرنساوي كبير', '', '', 60, 1, 4, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('turkish-coffee-قهوة-نوتيلا', 'قهوة نوتيلا', 'قهوة نوتيلا', '', '', 60, 1, 5, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('turkish-coffee-قهوة-محوج-small', 'قهوة محوج صغير', 'قهوة محوج صغير', '', '', 40, 1, 6, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('turkish-coffee-قهوة-محوج-large', 'قهوة محوج كبير', 'قهوة محوج كبير', '', '', 55, 1, 7, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('turkish-coffee-قهوة-بندق', 'قهوة بندق', 'قهوة بندق', '', '', 50, 1, 8, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('espresso-اسبرسو-small', 'اسبرسو صغير', 'اسبرسو صغير', '', '', 40, 2, 9, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('espresso-اسبرسو-large', 'اسبرسو كبير', 'اسبرسو كبير', '', '', 60, 2, 10, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('espresso-اسبرسو-ميكاتو-small', 'اسبرسو ميكاتو صغير', 'اسبرسو ميكاتو صغير', '', '', 50, 2, 11, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('espresso-اسبرسو-ميكاتو-large', 'اسبرسو ميكاتو كبير', 'اسبرسو ميكاتو كبير', '', '', 70, 2, 12, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('espresso-لاتيه', 'لاتيه', 'لاتيه', '', '', 70, 2, 13, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('espresso-كابتشينو', 'كابتشينو', 'كابتشينو', '', '', 65, 2, 14, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('espresso-اسبانيش-لاتيه', 'اسبانيش لاتيه', 'اسبانيش لاتيه', '', '', 80, 2, 15, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('espresso-كراميل-ميكاتو-small', 'كراميل ميكاتو صغير', 'كراميل ميكاتو صغير', '', '', 75, 2, 16, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('espresso-كراميل-ميكاتو-large', 'كراميل ميكاتو كبير', 'كراميل ميكاتو كبير', '', '', 85, 2, 17, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('espresso-امريكن-كوفي', 'امريكن كوفي', 'امريكن كوفي', '', '', 60, 2, 18, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('espresso-فلات-وايت', 'فلات وايت', 'فلات وايت', '', '', 75, 2, 19, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('espresso-موكا', 'موكا', 'موكا', '', '', 75, 2, 20, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('espresso-كورتادو', 'كورتادو', 'كورتادو', '', '', 75, 2, 21, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('espresso-V60-ايس', 'V60 ايس', 'V60 ايس', '', '', 120, 2, 22, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('espresso-V60-هوت', 'V60 هوت', 'V60 هوت', '', '', 120, 2, 23, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('hot-drinks-هوت-شوكليت', 'هوت شوكليت', 'هوت شوكليت', '', '', 70, 3, 24, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('hot-drinks-هوت-شوكليت-اوريو', 'هوت شوكليت اوريو', 'هوت شوكليت اوريو', '', '', 80, 3, 25, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('hot-drinks-هوت-شوكليت-نوتيلا', 'هوت شوكليت نوتيلا', 'هوت شوكليت نوتيلا', '', '', 80, 3, 26, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('hot-drinks-هوت-شوكليت-القاضي', 'هوت شوكليت القاضي', 'هوت شوكليت القاضي', '', '', 90, 3, 27, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('hot-drinks-هوت-شوكليت-سينابون', 'هوت شوكليت سينابون', 'هوت شوكليت سينابون', '', '', 75, 3, 28, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('hot-drinks-نسكافيه', 'نسكافيه', 'نسكافيه', '', '', 55, 3, 29, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('hot-drinks-شاي', 'شاي', 'شاي', '', '', 30, 3, 30, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('hot-drinks-شاي-نكهات', 'شاي نكهات', 'شاي نكهات', '', '', 35, 3, 31, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('hot-drinks-هوت-سيدر', 'هوت سيدر', 'هوت سيدر', '', '', 60, 3, 32, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('hot-drinks-اعشاب-كوكتيل', 'اعشاب كوكتيل', 'اعشاب كوكتيل', '', '', 45, 3, 33, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('iced-espresso-ايس-لاتيه', 'ايس لاتيه', 'ايس لاتيه', '', '', 85, 4, 34, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('iced-espresso-ايس-كراميل-ميكاتو', 'ايس كراميل ميكاتو', 'ايس كراميل ميكاتو', '', '', 85, 4, 35, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('iced-espresso-ايس-موكا', 'ايس موكا', 'ايس موكا', 'وايت / دارك', '', 85, 4, 36, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('iced-espresso-ايس-اسبانيش-لاتيه', 'ايس اسبانيش لاتيه', 'ايس اسبانيش لاتيه', '', '', 85, 4, 37, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('iced-espresso-ايس-امريكانو', 'ايس امريكانو', 'ايس امريكانو', '', '', 85, 4, 38, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('iced-espresso-ايس-كابتشينو', 'ايس كابتشينو', 'ايس كابتشينو', '', '', 85, 4, 39, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('iced-espresso-ايس-لاتيه-بستاشيو', 'ايس لاتيه بستاشيو', 'ايس لاتيه بستاشيو', '', '', 90, 4, 40, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('frappuccino-كوفي-فرابتشينو', 'كوفي فرابتشينو', 'كوفي فرابتشينو', '', '', 90, 5, 41, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('frappuccino-موكا-فرابتشينو', 'موكا فرابتشينو', 'موكا فرابتشينو', '', '', 90, 5, 42, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('frappuccino-فرابتشينو-ترمسيو', 'فرابتشينو ترمسيو', 'فرابتشينو ترمسيو', '', '', 120, 5, 43, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('frappuccino-فانيلا-فرابتشينو', 'فانيلا فرابتشينو', 'فانيلا فرابتشينو', '', '', 90, 5, 44, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('frappuccino-كراميل-فرابتشينو', 'كراميل فرابتشينو', 'كراميل فرابتشينو', '', '', 90, 5, 45, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('frappuccino-وايت-موكا-فرابتشينو', 'وايت موكا فرابتشينو', 'وايت موكا فرابتشينو', '', '', 90, 5, 46, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('frappuccino-نوتيلا-فرابتشينو', 'نوتيلا فرابتشينو', 'نوتيلا فرابتشينو', '', '', 95, 5, 47, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('frappuccino-كوفي-بستاشيو', 'كوفي بستاشيو', 'كوفي بستاشيو', '', '', 90, 5, 48, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('desserts-تشيز-كيك', 'تشيز كيك', 'تشيز كيك', '', '', 80, 6, 49, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('desserts-شوكيلت-كيك', 'شوكيلت كيك', 'شوكيلت كيك', '', '', 85, 6, 50, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('desserts-براونيز', 'براونيز', 'براونيز', '', '', 85, 6, 51, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('desserts-كوكيز', 'كوكيز', 'كوكيز', '', '', 85, 6, 52, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('desserts-ترامسيو', 'ترامسيو', 'ترامسيو', '', '', 85, 6, 53, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('desserts-ريد-فيلفيت', 'ريد فيلفيت', 'ريد فيلفيت', '', '', 85, 6, 54, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('desserts-سان-سبيستيان', 'سان سبيستيان', 'سان سبيستيان', '', '', 80, 6, 55, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('desserts-كيت-كات-كيك', 'كيت كات كيك', 'كيت كات كيك', '', '', 85, 6, 56, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('desserts-سيا-زبون', 'سيا زبون', 'سيا زبون', '', '', 80, 6, 57, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('desserts-مولتن-كيك', 'مولتن كيك', 'مولتن كيك', '', '', 90, 6, 58, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('desserts-ميني-شوكليت-كيك', 'ميني شوكليت كيك', 'ميني شوكليت كيك', '', '', 85, 6, 59, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('waffle-وافل-كراميل-شوكليت', 'وافل كراميل شوكليت', 'وافل كراميل شوكليت', '', '', 80, 7, 60, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('waffle-وافل-سيكريت-لافر', 'وافل سيكريت لافر', 'وافل سيكريت لافر', 'نوتيلا + كيندر + قطع شوكولاتة', '', 80, 7, 61, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('waffle-وافل-لوتس', 'وافل لوتس', 'وافل لوتس', '', '', 90, 7, 62, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('waffle-وافل-بستاشيو', 'وافل بستاشيو', 'وافل بستاشيو', '', '', 90, 7, 63, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('waffle-وافل-بلاك-اند-وايت', 'وافل بلاك اند وايت', 'وافل بلاك اند وايت', '', '', 85, 7, 64, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('waffle-وافل-وايت-بيري', 'وافل وايت بيري', 'وافل وايت بيري', '', '', 85, 7, 65, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('waffle-وافل-كواترو', 'وافل كواترو', 'وافل كواترو', 'نوتيلا + كراميل + شوكليت وايت + لوتس', '', 90, 7, 66, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('waffle-وافل-القاضي', 'وافل القاضي', 'وافل القاضي', 'نوتيلا + بستاشيو + كيندر + لوتس + فاكهة + مكسرات', '', 110, 7, 67, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('fruit-salad-فروت-سلطة', 'فروت سلطة', 'فروت سلطة', '', '', 100, 8, 68, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('fruit-salad-فروت-سلطة-تروبيكال', 'فروت سلطة تروبيكال', 'فروت سلطة تروبيكال', '', '', 150, 8, 69, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('fruit-salad-فروت-سلطة-القاضي', 'فروت سلطة القاضي', 'فروت سلطة القاضي', '', '', 200, 8, 70, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('ice-cream-ايس-كريم-3-بولة', 'ايس كريم 3 بولة', 'ايس كريم 3 بولة', '', '', 60, 9, 71, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('ice-cream-ايس-كريم-اوريو', 'ايس كريم اوريو', 'ايس كريم اوريو', '', '', 75, 9, 72, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('ice-cream-ايس-كريم-نوتيلا', 'ايس كريم نوتيلا', 'ايس كريم نوتيلا', '', '', 80, 9, 73, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('ice-cream-ايس-كريم-فواكه', 'ايس كريم فواكه', 'ايس كريم فواكه', '', '', 80, 9, 74, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('ice-cream-ايس-كريم-القاضي', 'ايس كريم القاضي', 'ايس كريم القاضي', '', '', 95, 9, 75, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('bakery-كرواسون-رومي-مدخن', 'كرواسون رومي مدخن', 'كرواسون رومي مدخن', '', '', 70, 10, 76, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('bakery-كرواسون-مكس-جبن', 'كرواسون مكس جبن', 'كرواسون مكس جبن', '', '', 75, 10, 77, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('bakery-كرواسون-روزبيف', 'كرواسون روزبيف', 'كرواسون روزبيف', '', '', 85, 10, 78, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('bakery-كرواسون-شوكليت', 'كرواسون شوكليت', 'كرواسون شوكليت', '', '', 70, 10, 79, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('bakery-كرواسون-ميجا', 'كرواسون ميجا', 'كرواسون ميجا', '', '', 90, 10, 80, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('bakery-ساندوتش-مكس-جبن', 'ساندوتش مكس جبن', 'ساندوتش مكس جبن', 'دقيق شوفان', '', 75, 10, 81, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('bakery-ساندوتش-رومي-مدخن', 'ساندوتش رومي مدخن', 'ساندوتش رومي مدخن', 'دقيق شوفان', '', 75, 10, 82, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('bakery-ساندوتش-روزبيف', 'ساندوتش روزبيف', 'ساندوتش روزبيف', 'دقيق شوفان', '', 85, 10, 83, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('extras-صوص', 'صوص', 'صوص', 'كراميل - شوكولاتة', '', 25, 11, 84, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('extras-صوص-فستق', 'صوص فستق', 'صوص فستق', '', '', 30, 11, 85, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('extras-نوتيلا', 'نوتيلا', 'نوتيلا', '', '', 30, 11, 86, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('extras-ويبد-كريم', 'ويبد كريم', 'ويبد كريم', '', '', 25, 11, 87, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('extras-ايس', 'ايس', 'ايس', '', '', 25, 11, 88, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('extras-فليفر-كراميل', 'فليفر كراميل', 'فليفر كراميل', '', '', 25, 11, 89, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('extras-فليفر-فانيلا', 'فليفر فانيلا', 'فليفر فانيلا', '', '', 25, 11, 90, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('extras-فليفر-بندق', 'فليفر بندق', 'فليفر بندق', '', '', 25, 11, 91, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('extras-فليفر-جوز-هند', 'فليفر جوز هند', 'فليفر جوز هند', '', '', 25, 11, 92, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('extras-توبينج-بلوبيري', 'توبينج بلوبيري', 'توبينج بلوبيري', '', '', 25, 11, 93, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('extras-توبينج-فراولة', 'توبينج فراولة', 'توبينج فراولة', '', '', 25, 11, 94, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('extras-شوت-اسبريسو', 'شوت اسبريسو', 'شوت اسبريسو', '', '', 35, 11, 95, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('extras-بوبا', 'بوبا', 'بوبا', '', '', 45, 11, 96, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('winter-specials-سحلب', 'سحلب', 'سحلب', '', '', 70, 12, 97, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('winter-specials-كريب', 'كريب', 'كريب', 'موز - فراولة - نوتيلا', '', 80, 12, 98, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('winter-specials-كريب-1', 'كريب', 'كريب', 'بستاشيو', '', 85, 12, 99, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('winter-specials-ام-علي-مكسرات', 'ام علي مكسرات', 'ام علي مكسرات', '', '', 130, 12, 100, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;
insert into menu_items (slug, name_ar, name_en, desc_ar, desc_en, price_egp, category_id, sort, is_available) values ('winter-specials-ام-علي-القاضي', 'ام علي القاضي', 'ام علي القاضي', '', '', 150, 12, 101, true) on conflict (slug) do update set name_ar=excluded.name_ar, name_en=excluded.name_en, desc_ar=excluded.desc_ar, price_egp=excluded.price_egp, category_id=excluded.category_id, sort=excluded.sort;

commit;
